import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { contrato_pages } from "./contrato.pages.ts";
import { contrato_tables } from "./contrato.tables.ts";

export const contrato_module = define_module({
  resource: "contrato",
  labels: {
    singular: "Contratos",
    plural: "Contratos",
    read: "Ver Contratos",
    write: "Editar Contratos",
  },
  routes: define_crud({
    resource: "contrato",
    table: "contrato",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "contrato",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      contrato: { type: "string", search: true },
      contribuyente: { type: "string", search: true },
      colonia: { type: "string", search: true },
      id_ruta: { type: "string", search: true },
      saldo: { type: "number" },
      tomada: { type: "boolean" },
      calle: { type: "string", search: true },
      poblacion: { type: "string", search: true },
      exterior: { type: "string", search: true },
      interior: { type: "string", search: true },
      consecutivo_ruta: { type: "number" },
      id_tarifa: { type: "string", search: true },
      serie_medidor: { type: "string", search: true },
      vigencia_anterior: { type: "number" },
      periodo_anterior: { type: "number" },
      lectura_anterior: { type: "number" },
      promedio: { type: "number" },
      adeudo: { type: "number" },
      recibe_lectura: { type: "boolean" },
      sincronizada: { type: "boolean" },
      sincronizado_simapa: { type: "boolean" },
      latitud: { type: "number" },
      longitud: { type: "number" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: contrato_tables,
  pages: contrato_pages,
  menu: [],
});
