import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const contrato_tables: KirletTableDecl[] = [
  {
    name: "contrato",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "contrato", type: "text" },
      { name: "contribuyente", type: "text" },
      { name: "colonia", type: "text" },
      { name: "id_ruta", type: "text" },
      { name: "saldo", type: "real" },
      { name: "tomada", type: "boolean" },
      { name: "calle", type: "text" },
      { name: "poblacion", type: "text" },
      { name: "exterior", type: "text" },
      { name: "interior", type: "text" },
      { name: "consecutivo_ruta", type: "real" },
      { name: "id_tarifa", type: "text" },
      { name: "serie_medidor", type: "text" },
      { name: "vigencia_anterior", type: "real" },
      { name: "periodo_anterior", type: "real" },
      { name: "lectura_anterior", type: "real" },
      { name: "promedio", type: "real" },
      { name: "adeudo", type: "real" },
      { name: "recibe_lectura", type: "boolean" },
      { name: "sincronizada", type: "boolean" },
      { name: "sincronizado_simapa", type: "boolean" },
      { name: "latitud", type: "real" },
      { name: "longitud", type: "real" },
    ],
    indexes: [
      { name: "idx_contrato_name", columns: ["name"] },
      { name: "idx_contrato_active", columns: ["is_active"] },
    ],
  },
];
