import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const citizen_report_tables: KirletTableDecl[] = [
  {
    name: "citizen_report",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "citizen_name", type: "text" },
      { name: "citizen_email", type: "text" },
      { name: "citizen_phone", type: "text" },
      { name: "citizen_street", type: "text" },
      { name: "building_number_external", type: "text" },
      { name: "building_number_internal", type: "text" },
      { name: "neighborhood", type: "text" },
      { name: "borough", type: "text" },
      { name: "delegado", type: "text" },
      { name: "report_description", type: "text" },
      { name: "materials_used", type: "text" },
      { name: "employee_taken_the_report", type: "text" },
      { name: "assinged_to", type: "text" },
      { name: "department", type: "text" },
      { name: "cuadrilla", type: "text" },
      { name: "jefe_de_cuadrilla", type: "text" },
      { name: "priority", type: "text" },
      { name: "status", type: "text" },
      { name: "citizen_report_problem", type: "text" },
      { name: "reporting_medium", type: "text" },
      { name: "evidence_before_images", type: "text" },
      { name: "evidence_after_images", type: "text" },
      { name: "report_coordinates", type: "text" },
      { name: "latitude", type: "real" },
      { name: "longitude", type: "real" },
      { name: "sequence", type: "real" },
      { name: "parent_report_id", type: "text" },
      { name: "source_instance_label", type: "text" },
      { name: "source_instance_url", type: "text" },
      { name: "public_submission", type: "boolean" },
    ],
    indexes: [
      { name: "idx_citizen_report_name", columns: ["name"] },
      { name: "idx_citizen_report_active", columns: ["is_active"] },
    ],
  },
];
