import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { citizen_report_pages } from "./citizen-report.pages.ts";
import { citizen_report_tables } from "./citizen-report.tables.ts";

export const citizen_report_module = define_module({
  resource: "citizen-report",
  labels: {
    singular: "Reportes",
    plural: "Reportes",
    read: "Ver Reportes",
    write: "Editar Reportes",
  },
  routes: define_crud({
    resource: "citizen-report",
    table: "citizen_report",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "citizen-",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      citizen_name: { type: "string", search: true },
      citizen_email: { type: "string", search: true },
      citizen_phone: { type: "string", search: true },
      citizen_street: { type: "string", search: true },
      building_number_external: { type: "string", search: true },
      building_number_internal: { type: "string", search: true },
      neighborhood: { type: "string", search: true },
      borough: { type: "string", search: true },
      delegado: { type: "string", search: true },
      report_description: { type: "string", search: true },
      materials_used: { type: "string", search: true },
      employee_taken_the_report: { type: "string", search: true },
      assinged_to: { type: "string", search: true },
      department: { type: "string", search: true },
      cuadrilla: { type: "string", search: true },
      jefe_de_cuadrilla: { type: "string", search: true },
      priority: { type: "string", search: true },
      status: { type: "string", search: true },
      citizen_report_problem: { type: "string", search: true },
      reporting_medium: { type: "string", search: true },
      evidence_before_images: { type: "string", search: true },
      evidence_after_images: { type: "string", search: true },
      report_coordinates: { type: "string", search: true },
      latitude: { type: "number" },
      longitude: { type: "number" },
      sequence: { type: "number" },
      parent_report_id: { type: "string", search: true },
      source_instance_label: { type: "string", search: true },
      source_instance_url: { type: "string", search: true },
      public_submission: { type: "boolean" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: citizen_report_tables,
  pages: citizen_report_pages,
  menu: [],
});
