import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { agua_pages } from "./agua.pages.ts";
import { agua_tables } from "./agua.tables.ts";

export const agua_module = define_module({
  resource: "agua",
  labels: {
    singular: "Parámetros",
    plural: "Parámetros",
    read: "Ver Parámetros",
    write: "Editar Parámetros",
  },
  routes: define_crud({
    resource: "agua",
    table: "agua",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "agua",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      vigencia_actual: { type: "number" },
      periodo_actual: { type: "number" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: agua_tables,
  pages: agua_pages,
  menu: [
    {
      id: "control-municipal.folder.citizen-report-menu-root",
      label: "Reporte ciudadano",
      order: 0,
      children: [
        {
          id: "control-municipal.citizen-report",
          label: "Reportes",
          order: 0,
          pageId: "control-municipal.citizen-report",
          path: "citizen-report",
          permission: "subject.control-municipal.citizen-report.read",
          icon: "document",
        },
        {
          id: "control-municipal.citizen-report-reporting-medium",
          label: "Medio de reporte",
          order: 0,
          pageId: "control-municipal.citizen-report-reporting-medium",
          path: "citizen-report-reporting-medium",
          permission: "subject.control-municipal.citizen-report-reporting-medium.read",
          icon: "document",
        },
        {
          id: "control-municipal.citizen-report-problem",
          label: "Tipo de problema",
          order: 0,
          pageId: "control-municipal.citizen-report-problem",
          path: "citizen-report-problem",
          permission: "subject.control-municipal.citizen-report-problem.read",
          icon: "document",
        },
        {
          id: "control-municipal.cuadrillas",
          label: "Cuadrillas",
          order: 20,
          pageId: "control-municipal.cuadrillas",
          path: "cuadrillas",
          permission: "subject.control-municipal.cuadrillas.read",
          icon: "document",
        }
      ],
    },
    {
      id: "control-municipal.folder.violation-menu-management-root",
      label: "Infracciones",
      order: 0,
      children: [
        {
          id: "control-municipal.municipality",
          label: "Municipios",
          order: 0,
          pageId: "control-municipal.municipality",
          path: "municipality",
          permission: "subject.control-municipal.municipality.read",
          icon: "document",
        },
        {
          id: "control-municipal.boroughs",
          label: "Delegaciones",
          order: 0,
          pageId: "control-municipal.boroughs",
          path: "boroughs",
          permission: "subject.control-municipal.boroughs.read",
          icon: "document",
        },
        {
          id: "control-municipal.states",
          label: "Estados",
          order: 0,
          pageId: "control-municipal.states",
          path: "states",
          permission: "subject.control-municipal.states.read",
          icon: "document",
        },
        {
          id: "control-municipal.violation",
          label: "Infracciones",
          order: 0,
          pageId: "control-municipal.violation",
          path: "violation",
          permission: "subject.control-municipal.violation.read",
          icon: "document",
        },
        {
          id: "control-municipal.violation-user-id-type",
          label: "Identificaciones válidas",
          order: 0,
          pageId: "control-municipal.violation-user-id-type",
          path: "violation-user-id-type",
          permission: "subject.control-municipal.violation-user-id-type.read",
          icon: "document",
        },
        {
          id: "control-municipal.violation-vehicle-brand",
          label: "Marcas de vehículos",
          order: 0,
          pageId: "control-municipal.violation-vehicle-brand",
          path: "violation-vehicle-brand",
          permission: "subject.control-municipal.violation-vehicle-brand.read",
          icon: "document",
        },
        {
          id: "control-municipal.violation-mobility-law",
          label: "Reglamento de Movilidad",
          order: 0,
          pageId: "control-municipal.violation-mobility-law",
          path: "violation-mobility-law",
          permission: "subject.control-municipal.violation-mobility-law.read",
          icon: "document",
        },
        {
          id: "control-municipal.violation-vehicle-type",
          label: "Tipos de vehículo",
          order: 0,
          pageId: "control-municipal.violation-vehicle-type",
          path: "violation-vehicle-type",
          permission: "subject.control-municipal.violation-vehicle-type.read",
          icon: "document",
        },
        {
          id: "control-municipal.violation-payment-method",
          label: "Métodos de pago",
          order: 0,
          pageId: "control-municipal.violation-payment-method",
          path: "violation-payment-method",
          permission: "subject.control-municipal.violation-payment-method.read",
          icon: "document",
        },
        {
          id: "control-municipal.violation-offender-guarantee",
          label: "Garantías del infractor",
          order: 0,
          pageId: "control-municipal.violation-offender-guarantee",
          path: "violation-offender-guarantee",
          permission: "subject.control-municipal.violation-offender-guarantee.read",
          icon: "document",
        },
        {
          id: "control-municipal.violation-city-zone",
          label: "Zonas de Ciudad",
          order: 0,
          pageId: "control-municipal.violation-city-zone",
          path: "violation-city-zone",
          permission: "subject.control-municipal.violation-city-zone.read",
          icon: "document",
        }
      ],
    },
    {
      id: "control-municipal.folder.agua-menu-root",
      label: "Agua potable",
      order: 1,
      children: [
        {
          id: "control-municipal.ruta",
          label: "Rutas",
          order: 1,
          pageId: "control-municipal.ruta",
          path: "ruta",
          permission: "subject.control-municipal.ruta.read",
          icon: "document",
        },
        {
          id: "control-municipal.contrato",
          label: "Contratos",
          order: 2,
          pageId: "control-municipal.contrato",
          path: "contrato",
          permission: "subject.control-municipal.contrato.read",
          icon: "document",
        },
        {
          id: "control-municipal.lecturista",
          label: "Lecturistas",
          order: 3,
          pageId: "control-municipal.lecturista",
          path: "lecturista",
          permission: "subject.control-municipal.lecturista.read",
          icon: "document",
        },
        {
          id: "control-municipal.tarifa",
          label: "Tarifas",
          order: 4,
          pageId: "control-municipal.tarifa",
          path: "tarifa",
          permission: "subject.control-municipal.tarifa.read",
          icon: "document",
        },
        {
          id: "control-municipal.impedimento",
          label: "Impedimentos",
          order: 5,
          pageId: "control-municipal.impedimento",
          path: "impedimento",
          permission: "subject.control-municipal.impedimento.read",
          icon: "document",
        },
        {
          id: "control-municipal.incidencia",
          label: "Incidencias",
          order: 6,
          pageId: "control-municipal.incidencia",
          path: "incidencia",
          permission: "subject.control-municipal.incidencia.read",
          icon: "document",
        },
        {
          id: "control-municipal.lectura-campo",
          label: "Captura de campo",
          order: 7,
          pageId: "control-municipal.lectura-campo",
          path: "lectura-campo",
          permission: "subject.control-municipal.lectura-campo.read",
          icon: "document",
        },
        {
          id: "control-municipal.periodo",
          label: "Periodos",
          order: 7,
          pageId: "control-municipal.periodo",
          path: "periodo",
          permission: "subject.control-municipal.periodo.read",
          icon: "document",
        },
        {
          id: "control-municipal.lectura",
          label: "Lecturas",
          order: 8,
          pageId: "control-municipal.lectura",
          path: "lectura",
          permission: "subject.control-municipal.lectura.read",
          icon: "document",
        },
        {
          id: "control-municipal.agua-reportes",
          label: "Reportes",
          order: 9,
          pageId: "control-municipal.agua-reportes",
          path: "agua-reportes",
          permission: "subject.control-municipal.agua-reportes.read",
          icon: "document",
        },
        {
          id: "control-municipal.agua-sync",
          label: "Sincronización",
          order: 10,
          pageId: "control-municipal.agua-sync",
          path: "agua-sync",
          permission: "subject.control-municipal.agua-sync.read",
          icon: "document",
        },
        {
          id: "control-municipal.agua",
          label: "Parámetros",
          order: 99,
          pageId: "control-municipal.agua",
          path: "agua",
          permission: "subject.control-municipal.agua.read",
          icon: "document",
        }
      ],
    },
    {
      id: "control-municipal.cobranza",
      label: "Cobranza",
      order: 1,
      pageId: "control-municipal.cobranza",
      path: "cobranza",
      permission: "subject.control-municipal.cobranza.read",
      icon: "document",
    }
    ],
});
