import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const violation_tables: KirletTableDecl[] = [
  {
    name: "violation",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "folio", type: "real" },
      { name: "code", type: "text" },
      { name: "plates", type: "text" },
      { name: "status", type: "text" },
      { name: "canceled_reason", type: "text" },
      { name: "canceled_by_id", type: "text" },
      { name: "condoned", type: "real" },
      { name: "condoned_reason", type: "text" },
      { name: "condoned_by_id", type: "text" },
      { name: "challenged_reason", type: "text" },
      { name: "challenged_by_id", type: "text" },
      { name: "offline_draft", type: "boolean" },
      { name: "img_reason_id", type: "text" },
      { name: "img_plate_id", type: "text" },
      { name: "state_id", type: "text" },
      { name: "vehicle_type_id", type: "text" },
      { name: "vehicle_brand_id", type: "text" },
      { name: "vehicle_year", type: "real" },
      { name: "color", type: "text" },
      { name: "service_type", type: "text" },
      { name: "administrative_arrest_commutable", type: "text" },
      { name: "partial_breathalyzer_report", type: "text" },
      { name: "uma_qty", type: "real" },
      { name: "uma_price", type: "real" },
      { name: "uma_total", type: "real" },
      { name: "uma_min", type: "real" },
      { name: "uma_max", type: "real" },
      { name: "article_id", type: "text" },
      { name: "article", type: "text" },
      { name: "fraction", type: "text" },
      { name: "police_officer_id", type: "text" },
      { name: "city_zone_id", type: "text" },
      { name: "img_signature_police_officer", type: "text" },
      { name: "img_signature_owner", type: "text" },
      { name: "img_signature_driver", type: "text" },
    ],
    indexes: [
      { name: "idx_violation_name", columns: ["name"] },
      { name: "idx_violation_active", columns: ["is_active"] },
    ],
  },
];
