import {
  build_feature_shell_page,
  type KirletPageDecl,
} from "@opus-perpetuus/imperium-core-kit";

const API = "api://m/subject-control-municipal";

export const violation_pages: KirletPageDecl[] = [
  {
    id: "control-municipal.violation",
    path: "violation",
    permission: "subject.control-municipal.violation.read",
    build: () =>
      build_feature_shell_page({
        id: "control-municipal.violation",
        owner: "subject-control-municipal",
        title: "Infracciones",
        props: {
          basePath: "violation",
          idKey: "id",
          nameKey: "name",
          view: {
            title: "Infracciones",
            subtitle: "Submenú de control-municipal",
            pluralLabel: "infracciones",
            singularLabel: "infracciones",
            emptyTitle: "Sin registros",
            emptyDescription: "Migra desde Mongo o crea el primero",
          },
          data: {
            list: `${API}/violation`,
            record: `${API}/violation/:id`,
            create: { method: "POST", action: `${API}/violation` },
            update: { method: "PATCH", action: `${API}/violation/:id` },
            delete: { method: "DELETE", action: `${API}/violation/:id` },
          },
          table: {
            columns: [
              { key: "name", label: "Nombre", sortable: true, priority: 1 },
              { key: "is_active", label: "Activo", sortable: true, priority: 2 },
              { key: "ref", label: "Ref", sortable: true, priority: 3 },
              { key: "folio", label: "folio", sortable: true, priority: 3 },
              { key: "code", label: "code", sortable: true, priority: 3 },
              { key: "plates", label: "plates", sortable: true, priority: 3 },
              { key: "status", label: "status", sortable: true, priority: 3 },
              { key: "canceled_reason", label: "canceled reason", sortable: true, priority: 3 },
              { key: "canceled_by_id", label: "canceled by id", sortable: true, priority: 3 },
            ],
            fillHeight: true,
            serverQuery: true,
          },
          form: {
            fields: [
              { name: "name", component: "input-text", label: "Nombre", required: true },
              { name: "description", component: "input-text", label: "Descripción" },
              { name: "ref", component: "input-text", label: "Referencia (_ref)" },
              { name: "folio", component: "input-number", label: "folio" },
              { name: "code", component: "input-text", label: "code" },
              { name: "plates", component: "input-text", label: "plates" },
              { name: "status", component: "input-text", label: "status" },
              { name: "canceled_reason", component: "input-text", label: "canceled reason" },
              { name: "canceled_by_id", component: "input-text", label: "canceled by id" },
              { name: "condoned", component: "input-number", label: "condoned" },
              { name: "condoned_reason", component: "input-text", label: "condoned reason" },
              { name: "condoned_by_id", component: "input-text", label: "condoned by id" },
              { name: "challenged_reason", component: "input-text", label: "challenged reason" },
              { name: "challenged_by_id", component: "input-text", label: "challenged by id" },
              { name: "offline_draft", component: "input-checkbox", label: "offline draft" },
              { name: "img_reason_id", component: "input-text", label: "img reason id" },
              { name: "img_plate_id", component: "input-text", label: "img plate id" },
              { name: "state_id", component: "input-text", label: "state id" },
              { name: "vehicle_type_id", component: "input-text", label: "vehicle type id" },
              { name: "vehicle_brand_id", component: "input-text", label: "vehicle brand id" },
              { name: "vehicle_year", component: "input-number", label: "vehicle year" },
              { name: "color", component: "input-text", label: "color" },
              { name: "service_type", component: "input-text", label: "service type" },
              { name: "administrative_arrest_commutable", component: "input-text", label: "administrative arrest commutable" },
              { name: "partial_breathalyzer_report", component: "input-text", label: "partial breathalyzer report" },
              { name: "uma_qty", component: "input-number", label: "uma qty" },
              { name: "uma_price", component: "input-number", label: "uma price" },
              { name: "uma_total", component: "input-number", label: "uma total" },
              { name: "uma_min", component: "input-number", label: "uma min" },
              { name: "uma_max", component: "input-number", label: "uma max" },
              { name: "article_id", component: "input-text", label: "article id" },
              { name: "article", component: "input-text", label: "article" },
              { name: "fraction", component: "input-text", label: "fraction" },
              { name: "police_officer_id", component: "input-text", label: "police officer id" },
              { name: "city_zone_id", component: "input-text", label: "city zone id" },
              { name: "img_signature_police_officer", component: "input-text", label: "img signature police officer" },
              { name: "img_signature_owner", component: "input-text", label: "img signature owner" },
              { name: "img_signature_driver", component: "input-text", label: "img signature driver" },
            ],
          },
        },
      }),
  },
];
