import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { violation_pages } from "./violation.pages.ts";
import { violation_tables } from "./violation.tables.ts";

export const violation_module = define_module({
  resource: "violation",
  labels: {
    singular: "Infracciones",
    plural: "Infracciones",
    read: "Ver Infracciones",
    write: "Editar Infracciones",
  },
  routes: define_crud({
    resource: "violation",
    table: "violation",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "violatio",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      folio: { type: "number" },
      code: { type: "string", search: true },
      plates: { type: "string", search: true },
      status: { type: "string", search: true },
      canceled_reason: { type: "string", search: true },
      canceled_by_id: { type: "string", search: true },
      condoned: { type: "number" },
      condoned_reason: { type: "string", search: true },
      condoned_by_id: { type: "string", search: true },
      challenged_reason: { type: "string", search: true },
      challenged_by_id: { type: "string", search: true },
      offline_draft: { type: "boolean" },
      img_reason_id: { type: "string", search: true },
      img_plate_id: { type: "string", search: true },
      state_id: { type: "string", search: true },
      vehicle_type_id: { type: "string", search: true },
      vehicle_brand_id: { type: "string", search: true },
      vehicle_year: { type: "number" },
      color: { type: "string", search: true },
      service_type: { type: "string", search: true },
      administrative_arrest_commutable: { type: "string", search: true },
      partial_breathalyzer_report: { type: "string", search: true },
      uma_qty: { type: "number" },
      uma_price: { type: "number" },
      uma_total: { type: "number" },
      uma_min: { type: "number" },
      uma_max: { type: "number" },
      article_id: { type: "string", search: true },
      article: { type: "string", search: true },
      fraction: { type: "string", search: true },
      police_officer_id: { type: "string", search: true },
      city_zone_id: { type: "string", search: true },
      img_signature_police_officer: { type: "string", search: true },
      img_signature_owner: { type: "string", search: true },
      img_signature_driver: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: violation_tables,
  pages: violation_pages,
  menu: [],
});
