import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const lectura_tables: KirletTableDecl[] = [
  {
    name: "lectura",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "contrato", type: "text" },
      { name: "lectura_actual", type: "real" },
      { name: "consumo_mts3", type: "real" },
      { name: "importe", type: "real" },
      { name: "fecha_lectura", type: "text" },
      { name: "contrato_id", type: "text" },
      { name: "vigencia", type: "real" },
      { name: "periodo", type: "real" },
      { name: "lectura_anterior", type: "real" },
      { name: "mts3_cobrados", type: "real" },
      { name: "id_tarifa", type: "text" },
      { name: "id_impedimento", type: "text" },
      { name: "id_incidencia", type: "text" },
      { name: "id_lecturista", type: "text" },
      { name: "id_ruta", type: "text" },
      { name: "observaciones", type: "text" },
      { name: "latitud", type: "real" },
      { name: "longitud", type: "real" },
      { name: "estado", type: "text" },
      { name: "sincronizado_simapa", type: "boolean" },
    ],
    indexes: [
      { name: "idx_lectura_name", columns: ["name"] },
      { name: "idx_lectura_active", columns: ["is_active"] },
    ],
  },
];
