import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { lectura_pages } from "./lectura.pages.ts";
import { lectura_tables } from "./lectura.tables.ts";

export const lectura_module = define_module({
  resource: "lectura",
  labels: {
    singular: "Lecturas",
    plural: "Lecturas",
    read: "Ver Lecturas",
    write: "Editar Lecturas",
  },
  routes: define_crud({
    resource: "lectura",
    table: "lectura",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "lectura",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      contrato: { type: "string", search: true },
      lectura_actual: { type: "number" },
      consumo_mts3: { type: "number" },
      importe: { type: "number" },
      fecha_lectura: { type: "string", search: true },
      contrato_id: { type: "string", search: true },
      vigencia: { type: "number" },
      periodo: { type: "number" },
      lectura_anterior: { type: "number" },
      mts3_cobrados: { type: "number" },
      id_tarifa: { type: "string", search: true },
      id_impedimento: { type: "string", search: true },
      id_incidencia: { type: "string", search: true },
      id_lecturista: { type: "string", search: true },
      id_ruta: { type: "string", search: true },
      observaciones: { type: "string", search: true },
      latitud: { type: "number" },
      longitud: { type: "number" },
      estado: { type: "string", search: true },
      sincronizado_simapa: { type: "boolean" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: lectura_tables,
  pages: lectura_pages,
  menu: [],
});
